### ISSUE TITLE
Can you add a LICENSE file?

### ISSUE THREAD

**Issue by KFishner** [contiv/objdb#21]
Seems like all other Contiv projects are Apache 2.0, can you add that to this repo as well?

https://github.com/contiv/netplugin/blob/master/LICENSE
https://github.com/contiv/ofnet/blob/master/LICENSE

**Comment by dseevr** [comment]
Hi @KFishner,

We have an internal issue to add LICENSE files to our repos.  Rest assured, it's being tracked.  :)

**Comment by KFishner** [comment]
@dseevr great. any estimated timeline for that?

**Comment by dseevr** [comment]
I can't provide any estimates for it right now 🙁 

I'll reply to this issue once it's done, though.

**Comment by dseevr** [comment]
objdb is now officially licensed.  I've also received permission to license all our other repos as well.

Thanks for the kick in the pants!
